### ISSUE TITLE
automate问题请教一下。

### ISSUE THREAD

**Issue by eko5624** [dyphire/mpv-win64#1]
真心求教个问题。因为我不是学软件的，好多东西搞不明白。有个问题困扰了我好多天了。google出的答案也是一知半解。您如果能帮我解惑就太感谢了。

我仓库里这个autoupdate老是运行失败是什么原因。我已经在个人账号里设置了PAT。然后在mpv-win64仓库里也设置了仓库secret。是不是autoupdate.py编写的不对，还是其他哪里的问题？求指导。。

**Comment by dyphire** [comment]
同代码小白，我还是抄的你的作业，autoupdate好像就没怎么改过  :joy:。失败应该是跟autoupdate.py有关，它没有检测到更新时就会失败，所以我自动运行设的一周一次降低失败概率，抱歉帮不到你 :sweat:

**Comment by dyphire** [comment]
建议问下autoupdate.py的原作者怎么改进比较快一些

**Comment by eko5624** [comment]
好的，谢谢回复
